### ISSUE TITLE
cert files are not removed from temp dir

### ISSUE THREAD

**Issue by eoff** [lightbody/browsermob-proxy#101] opened 2014-09-22 16:02 UTC
because of this line 

https://github.com/lightbody/browsermob-proxy/blob/master/src/main/java/net/lightbody/bmp/proxy/BrowserMobProxyHandler.java#L98 

temp dirs (like "seleniumSslSupport4265958041609732267ar.tns-counter.ru") are not removed when proxy server is closed:
https://github.com/lightbody/browsermob-proxy/blob/master/src/main/java/net/lightbody/bmp/proxy/selenium/SeleniumProxyHandler.java#L770

it seems to be bad to leave files in temp dir and don't remove them. is there a way to fix this problem?

**Comment by aboschee** [comment] 2015-02-09 14:02
The above links no longer work.
It's the line: 
relay.setNukeDirOrFile(null);
in the method:
BrowserMobProxyHandler.getSslRelayOrCreateNew

The delete should be called from the following, but isn't because the file is set to null (above):
SeleniumProxyHander.SslRelay.stop

**Comment by jekh** [comment] 2015-02-10 01:20
This should actually be fixed by PR #170.

**Comment by jekh** [comment] 2015-02-13 18:54
I just merged 170 to master. @aboschee or @eoff -- if you're able to retest your scenario with the latest code, can you confirm that the temp files are now deleted? You'll probably want to delete all the "selenium..." directories in /tmp or c:\temp first, to clean out the old ones.

**Comment by aboschee** [comment] 2015-02-16 15:48
This issue still exists. The problem is that the value of SslRelay.nukeDirOrFile is null when attempting to delete the file. See my previous comment.

**Comment by jekh** [comment] 2015-02-17 05:14
@aboschee - I just pushed another change that should fix it. Let me know if you still experience the issue. Remember to remove any old files in /tmp before testing.

**Comment by aboschee** [comment] 2015-02-17 14:05
It's working for me, thanks!

**Comment by jekh** [comment] 2015-02-17 19:07
Great! I'll close this issue.

**Closed by jekh** 2015-02-17 19:07 UTC
