### ISSUE TITLE
Incorrect timings.wait values

### ISSUE THREAD

**Issue by romovs** [lightbody/browsermob-proxy#288] opened 2015-07-22 07:45 UTC
I was running some tests against the latest master and some of the recorded HARs contain suspiciously high wait times which can't be possibly right:
```
timings:{
    "connect":60,
    "blocked":0,
    "receive":0,
    "dns":4,
    "send":87,
    "ssl":-1,
    "wait":8983498276
}
```
That's almost 104 days of waiting!
Unfortunately I don't have a reproducible test case atm as it very rare. Will try to add some logging to the proxy and re-run everything soon, hopefully that will shed more light.

**Comment by romovs** [comment] 2015-07-22 16:50
More details:

sendFinishedNanos is occasionally 0 at this line, hence the gigantic 'wait' value:
https://github.com/lightbody/browsermob-proxy/blob/master/browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/HarCaptureFilter.java#L688

However judging by the logs it's definitely **not** due to System.nanoTime() returning 0 at https://github.com/lightbody/browsermob-proxy/blob/master/browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/HarCaptureFilter.java#L678

This seem to happen only if I run multiple proxies in parallel and also start new pageRefs:

- Create two proxy instances
- Run two selenium tests in parallel via each proxy
- During each test new pageRef is started multiple times
- Once a test is finished - HAR is fetched and the freed up proxy is disposed.

Also I am not sure if this is related, but just in case it's something to do with the pageRef switching - one time the returned HAR had an orphaned entry without a pageRef field (in that case though wait value was correct). It happened exactly when a new pageRef was requested:

```
      {
        "pageref": "Login",
        "startedDateTime": "2015-07-22T15:57:48.102+02:00",
        ...
      },
      {
        "pageref": "Login",
        "startedDateTime": "2015-07-22T15:57:48.667+02:00",
        ...
      },
      {
        "startedDateTime": "2015-07-22T15:57:48.708+02:00",
        ...
      },
      {
        "pageref": "Search",
        "startedDateTime": "2015-07-22T15:57:48.743+02:00",
        ...
      },
      {
        "pageref": "Search",
        "startedDateTime": "2015-07-22T15:57:48.790+02:00",
        ...
      },
```

**Comment by romovs** [comment] 2015-07-23 06:33
pageRef was a red herring. It's most likely unrelated.
Main issue seems to be that `HarCapture.serverToProxyResponseReceiving` is sometimes invoked before `HarCapture.proxyToServerRequestSent`

**Comment by jekh** [comment] 2015-07-23 22:39
Wow, thank you so much for tracking this down and pointing out exactly where the issue is. It's extremely helpful. The fix for this is pretty simple, and I have it working locally, but I want to add some better unit tests before I merge. So hang tight for just a bit longer. Thanks again, @romovs!

**Comment by romovs** [comment] 2015-07-30 10:12
By the way, same issue with the `receive` field.

**Comment by jekh** [comment] 2015-08-12 00:18
Update for interested parties: I've done a fair amount of investigation into this, and I'll push the short-term "fix" momentarily. The only thing holding me back has been the lack of proper tests, because it's actually a difficult scenario to test for without a huge amount of netty mocking. For now I'll commit then simple fixes so folks don't have to work around this manually, and back-burner the tests.

**Comment by jekh** [comment] 2015-08-12 02:45
This should now be fixed in master. @romovs - could you let me know if you still see problems with it?

**Comment by romovs** [comment] 2015-08-13 06:33
It works well now. Thanks jekh!

**Comment by jekh** [comment] 2015-09-01 04:29
Since this is working now, I'll go ahead and close this issue.

**Closed by jekh** 2015-09-01 04:29 UTC
