### ISSUE TITLE
Null content in response (HTTPS)

### ISSUE THREAD

**Issue by dimand58** [lightbody/browsermob-proxy#374] opened 2016-01-13 20:17 UTC
Thanks for greate library.
I have issue with latest version:
1) In real browser (BMob off) I open HTTPS page and click on some button
2) After few second I get response with some file (and Content-Type, Content-Disposition in header)
Always is OK

When I use BMob:
1) In real browser (BMob on) I open HTTPS page and click on some button
2) During debug I see correct response headers (with Content-Type, Content-Disposition), but contents is null. Expected - some bytes (file)
How it possible?

**Comment by jekh** [comment] 2016-01-13 20:49
What site are you visiting? Hard to say what's happening without some steps to reproduce, including a website or self-contained test case to test against. What version of BMP are you using? (Use 2.1.0-beta-4 or build from source.) What options are you setting in BMP? Are you running embedded, for example within Selenium tests, or are you using the REST API?

We need more information to help you out.

**Comment by Zap4ick** [comment] 2016-02-12 06:08
Hello dimand58, have you solved your problem? I have the same issue but with application/json type, where response.getEntry().getResponse().getContent.getText() is null, whet the size iz not 0 and it's not empty in fiddler.

**Comment by jekh** [comment] 2016-03-13 22:39
I'll close this since there's been no further info.

**Closed by jekh** 2016-03-13 22:39 UTC
