### ISSUE TITLE
"The connection was reset" after 20s of inactivity

### ISSUE THREAD

**Issue by m-architek** [lightbody/browsermob-proxy#173] opened 2015-02-11 11:45 UTC
Hello,

few days ago I face strange issue and I have no idea what can I do about it.

I wrote automatic test script using Selenium Webdriver with Browsermob-proxy and on one of my sites I've got an error "The connection was reset" after some time of proxy inactivity. 

I cannot reproduce it on other sites, but this one.
Without time of inactivity or without using proxy everything works fine.

Here is the code that reproduce the problem:

	/*
	 * Example test, create to reproduce the problem.
	 */
	public static void main(String[] args) {
		ProxyServer server = new ProxyServer(8094); // net.lightbody.bmp.proxy
		WebDriver driver = null;
		try {
			server.setLocalHost(InetAddress.getByName("localhost"));
			server.start();
			DesiredCapabilities caps = DesiredCapabilities.firefox();
			Proxy proxy = server.seleniumProxy();
			caps.setCapability(CapabilityType.PROXY, proxy);
			driver = new FirefoxDriver(caps);
			driver.manage().timeouts().implicitlyWait(3, TimeUnit.SECONDS);
			driver.get("http://answear.com/p/odziez-203-k.html");
			Thread.sleep(20 * 1000); // in my proper test here is the operation
										// in site's CMS which lasts abut half a
										// minute, it is perform on another
										// WebDriver instance and it don't use
										// bmp proxy
			driver.get("http://answear.com/p/odziez-229-k.html");
			// "The connection was reset" come out, after putting "Thread.sleep(..)"
			// in comment it works fine
			driver.findElement(By.cssSelector("a.thumb")).click();
			System.out.println("End of test");
		} catch (Exception e) {
			e.printStackTrace();
		} finally {
			if (driver != null)
				driver.quit();
			server.stop();
		}
	}

Tools:
Firefox: 35.0.1
Selenium: 2.44.0
Browsermob-proxy: 2.0-beta-10-SNAPSHOT

I will be grateful for any help.

**Comment by jekh** [comment] 2015-02-12 01:31
I tested this using the latest version of BMP that is currently in master (2.1.0-beta-1), and I wasn't able to reproduce. The output looks like:
```
...
2015-02-11 17:17:38,603 INFO [SocketListener0-44] net.lightbody.bmp.proxy.jetty.http.SocketListener - Started SocketListener on 0.0.0.0:33625
2015-02-11 17:17:38,841 INFO [SocketListener0-45] net.lightbody.bmp.proxy.jetty.http.SocketListener - Started SocketListener on 0.0.0.0:44357
2015-02-11 17:18:08,929 INFO [SocketListener0-42] net.lightbody.bmp.proxy.jetty.http.SocketListener - Started SocketListener on 0.0.0.0:47320
End of test
2015-02-11 17:18:10,866 INFO [Acceptor [SSL: ServerSocket[addr=0.0.0.0/0.0.0.0,localport=35193]]] net.lightbody.bmp.proxy.jetty.util.ThreadedServer - Stopping Acceptor [SSL: ServerSocket[addr=0.0.0.0/0.0.0.0,localport=35193]]
2015-02-11 17:18:10,969 INFO [main] net.lightbody.bmp.proxy.jetty.http.SocketListener - Stopped SocketListener on 0.0.0.0:35193
2015-02-11 17:18:10,970 INFO [Acceptor [SSL: ServerSocket[addr=0.0.0.0/0.0.0.0,localport=50496]]] net.lightbody.bmp.proxy.jetty.util.ThreadedServer - Stopping Acceptor [SSL: ServerSocket[addr=0.0.0.0/0.0.0.0,localport=50496]]
...

```
The test appears to run to completion without the connection reset message, and I can see Firefox loading the 2nd URL correctly.

Since you're currently using an older version, I'd suggest attempting to reproduce on the [latest released version, 2.0.0](https://github.com/lightbody/browsermob-proxy/releases/tag/browsermob-proxy-2.0.0), which is available in [Maven Central](http://mvnrepository.com/artifact/net.lightbody.bmp/browsermob-proxy/2.0.0). You can also try the 2.1.0-beta-1 release that is currently in master.

Have you tried testing against another domain, e.g. make a request to www.google.com, wait 20s, then make another request to www.google.com?

BTW - thank you for the self-contained test case. Very helpful!

**Comment by m-architek** [comment] 2015-02-12 10:48
Thanks for your support. 
Fact, that you couldn't reproduce it brings me another idea and I think I've found the cause of this problem.

I had some sort of extra dependency in my pom.xml:

		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpclient</artifactId>
			<version>4.4-beta1</version>
		</dependency>

after deleting it, code seems to work fine. So, I think thats it. :)


> Have you tried testing against another domain, e.g. make a request to www.google.com

Yes, it worked fine with google. Problem occurred only with domain that I put in exmaple code.


Regards

**Comment by jekh** [comment] 2015-02-12 18:02
Oh great, thanks @m-architek for double-checking that. BMP uses httpclient 4.3. I'll close this since it seems to be resolved now.

BMP isn't tested against httpclient 4.4-beta1, but when 4.4 is officially released I'll see if BMP is able to remain compatible with it.

**Closed by jekh** 2015-02-12 18:02 UTC
