### ISSUE TITLE
REST Response Intercept inconsistent behavior

### ISSUE THREAD

**Issue by borick** [lightbody/browsermob-proxy#399] opened 2016-03-11 14:57 UTC
I have an issue for REST API interception for modifying Response content. It works randomly depending on sequence of http/https calls. 

Sometimes it doesn't process the URLs coming in at all, and other times I get "null" error on contents.setTextContents....

By inspecting the code it relies on "HTTP message aggregation" or some such thing, the code says in browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/Response/RequestFilterAdapter.java

"HTTP message aggregation will be enabled if any filter has a maximum request or response buffer size greater than 0." but this doesn't seem to always work for me. Sometimes requests just aren't processed. Other-times they are but contents is set to null and I get a null pointer error. I had this working by some fluke combination of HTTP requests but figured out over last day or so that the robustness of this functionality is like spinning plates. I haven't been able to determine exactly what is causing this, tried a whole bunch of different things and looked at debug log. It does seem to happen for more "complex" requests, whatever that means, harder to reproduce in an isolated example, but was still able to.

Any explanation of why I'm seeing this behavior would be greatly appreciated. If you need anything from me on this to reproduce, let me know.

I'm now looking into other available proxy solutions now or something that can be done at JavaScript layer, but not much is out there that I can find.

 Thanks

**Comment by jekh** [comment] 2016-03-13 16:51
How large are the HTTP messages you're processing? The default maximum is 2 MB, and if the messages are larger than that, you'll definitely experience problems with Javascript filters. This is done intentionally to prevent one large or malicious message from bringing down the JVM. The default can be overridden quite easily in code, though the REST API doesn't expose this functionality. It would be quite trivial to add, so if that's the problem you're facing, I'd be willing to add it to the creaky old REST API (which is going to be replaced in a forthcoming release)..

If you have any stack traces, that'd be quite helpful.

**Comment by borick** [comment] 2016-03-13 17:43
Not that large! But in my case html files with a bunch of resources within, don't think limit is the reason as sometimes it works depending on sequence of calls. I don't get any stack traces. For example to debug I tried to simply make the response filter  log all files it's processing using log.info and a bunch of files depending on http sequence just aren't listed in log output. (i actually was also trying this with snapshot compiled increase maximum to 20mb for other reasons but had no difference in effect..)

for example if I process an https request and then http, it works. but if all requests are https it doesn't work. it's so strange, but it does behave consistently, i.e. it's not random so much but behavior is dependent on specific sequence of calls and/or the web-content I'm loading (and perhaps also some network conditions.)

I ended up finding another solution for my needs which was to create my own kind of proxy http server that modifies response content. Thanks for the reply.

**Comment by jekh** [comment] 2016-03-13 18:25
Do you have an example URL that will reproduce this issue? I'd like to try to solve this if possible, since other people are probably running into the same issue. In general, the request and response modification should work extremely well, as long as you're using the LittleProxy implementation (which is the default in beta-4).

**Comment by borick** [comment] 2016-03-13 20:04
is there any way i can provide the details in non-public forum, for confidentiality reasons? it's not a specific url but rather a sequence of calls, where some resources are just "skipped" and/or contents is set to null. it seems like the first url in the sequence is checked but then attempt to load same url again and another url, and both are "skipped"

i have a script where i was able to (at least locally) reproduce this fairly consistently. i'm also doing this in nodejs using browsermob-node & selenium, not sure if that makes a difference. just ran it again for example, still happening.

**Comment by jekh** [comment] 2016-03-13 23:29
Can you reproduce the issue against a public website? That would be the best test case, in the spirit of transparent open source development.

**Comment by jekh** [comment] 2016-04-23 21:34
Since there's no public website to test against, I'll close this issue. Feel free to reopen with more information.

**Closed by jekh** 2016-04-23 21:34 UTC
