### ISSUE TITLE
HttpMessageContents is null for chunked response

### ISSUE THREAD

**Issue by crazyk2** [lightbody/browsermob-proxy#491] opened 2016-07-05 14:55 UTC
I try to change content for response 
```json
DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
HTTP/1.1 200 OK
Server: nginx
Date: Tue, 05 Jul 2016 14:45:21 GMT
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
X-Node-Id: wms
X-Context-Id: PEOXQYZVIWKJJ1
X-API-Maturity: stable
X-Application-Context: application:11018
Via: 1.1 browsermobproxy
```
but content in response filter everytime is null
```java
public static ResponseFilter errorFilter(String urlRegexp, String errorMessage, String errorCode) {

        return (response, contents, messageInfo) -> {

            if (messageInfo.getOriginalUrl().matches(urlRegexp)) {
                if (contents == null){
                    LOG.error("Contents is null");
                    return;
                }
               // messageInfo.getChannelHandlerContext().
                ObjectMapper mapper = new ObjectMapper();
                try {
                    String a = mapper.writeValueAsString(new JsonError(messageInfo.getOriginalUrl(),errorMessage,"Stacktrace", errorCode));
                    //for debud String b = contents.getContentType();
                    contents.setTextContents(a);
                } catch (JsonProcessingException e) {
                    LOG.error("Can't read object to JSON string: " + e);
                    System.exit(1);
                }
            }
        };
    }
```
how can i read and change response contents.

pom.xml
```xml
<dependency>
            <groupId>net.lightbody.bmp</groupId>
            <artifactId>browsermob-core</artifactId>
            <version>2.1.1</version>
            <exclusions>
                <exclusion>
                    <groupId>org.seleniumhq.selenium</groupId>
                    <artifactId>selenium-api</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

**Comment by jekh** [comment] 2016-07-09 22:18
How are you adding the ResponseFilter to BMP, and when are you doing so? The DefaultHttpResponse you pasted suggests that netty's HTTP aggregation is disabled, which would cause the `contents` to be null. Aggregation is enabled automatically when adding a filter using BrowserMobProxy.addResponseFilter(), so it's puzzling that it would be disabled.

**Comment by crazyk2** [comment] 2016-07-14 13:17
This issue to LittleProxy I think.
I researched a problem.
I made several experiments. At first I included a proxy and I added the filter necessary to me and I launched the test. Aggregation worked as it is necessary. 
But when I changed execution order of steps, aggregation sometimes worked, sometimes not.

```java
loadUrl(URL_TMP).addFilter(URL_PATTERN_DEPOSITS, DepositInfoDto.class)
                .goToDeposiList()
				.goToDeposit(text(getObject().getProductName(), getObject().getOpenDate(), getObject().getExpDate()))
                .assertThat()
                .commonBodyShouldBe(visible)
                .extraInfoShouldBe(hidden)
                .clientName(getObject().getProductName())
                .name(getObject().getProductName())
                .percent(contract.getPercent())
                .percentPayPeriod(getObject().getPercentFrequency())
                .amount(contract.getBalance().getAmount() + contract.getBalance().getCurrency())
                .status(getObject().getStatus().getValue())

                .build();	
```		
I added Filter when Browser loadded URL and LittleProxy started all ```incoming and outgoing worker threads``` and ```initChannelPipeline``` was done.

If my packet recived and LittleProxy reused "existing connection"
`13:38:41,095 DEBUG LittleProxy-0-ClientToProxyWorker-4 ProxyToServerConnection:write:343 - (AWAITING_INITIAL) [id: 0x23675ff3, L:/127.0.0.1:64228 - R:roox1.open.ru/10.48.114.22:80]: Using existing connection to: roox1.open.ru/10.48.114.22:80
`
```initChannelPipeline``` wasn't executed and didn't call ```getMaximumResponseBufferSizeInBytes()``` and did not call ```aggregateContentForFiltering(pipeline, numberOfBytesToBuffer);``` then aggregation didn't work.

But if all connections closed (died) then LittleProxy start new connection

`14:43:29,026 DEBUG LittleProxy-0-ClientToProxyWorker-4 ProxyToServerConnection:connectAndWrite:544 - (DISCONNECTED) [id: 0xb5bf28bf, L:/127.0.0.1:59861 ! R:roox1.open.ru/10.48.114.22:80]: Starting new connection to: roox1.open.ru/10.48.114.22:80
`
and 

`14:43:29.027 [LittleProxy-0-ProxyToServerWorker-2] DEBUG ru.open.automation.qa.listeners.MyResponseFilterAdapter$FilterSource - Thread[main,5,main]; getMaximumResponseBufferSizeInBytes: 5097152`

and aggregation works fine.

Expected

Connections reinitialize when I add new ```HttpFiltersSource``` and check new ```maximumResponseBufferSizeInBytes/maximumRequestBufferSizeInBytes```.

**Comment by jekh** [comment] 2016-07-19 14:59
It sounds like the problem is that you're adding the filter after connections have already been established. The filters are not designed to work this way; add the filter first, then begin making connections through the browser/HTTP client. Since you noted that that seems to solve the problem, I'll go ahead and close this issue.

**Closed by jekh** 2016-07-19 14:59 UTC
