### ISSUE TITLE
Request URL captured shows the "remapped IP" instead of domain when making secure request

### ISSUE THREAD

**Issue by davidkohr** [lightbody/browsermob-proxy#178] opened 2015-02-19 03:04 UTC
Hello hello,

I'm using Selenium 2.44.0 with the new 2.0.0 browsermob proxy. It fixed a bunch of issues for me and it made me so happy that I broke my mug while jumping out of my chair, but I have to report this other issue.

I have to make some insecure requests (http://), and some secure requests (https://).

When I capture the requests/responses when insecure requests are made, everything is fine.

But when I do the same when making secure requests, I see this when I use "harRequest.getUrl()": https://1.2.3.4/...

The request URL is actually like "https://somedomain.com/..." but the IP shows up instead of the domain.

I am indeed using "server.remapHost" to map "somedomain.com" to "1.2.3.4".

This is a bug right? Anyone else experiencing this?

**Comment by jekh** [comment] 2015-02-19 03:44
Hi @davidkohr - you're right, that behavior would be a bug. The hostname in the HAR should be consistent between HTTP and HTTPS.

As for what it "should" be... I think there is an argument both ways, with either the original host or the remapped host in the HAR file. In your case you expect the original request's hostname to show up in the HAR, but I'd be interested to see what other people expect.

If the issue is serious enough for you, I'd welcome a PR against the 2.0 branch to make the behavior consistent for the (eventual) 2.0.1 bugfix release.

**Comment by jekh** [comment] 2016-07-19 15:04
Since this behavior is consistent now, I'll close this issue.

**Closed by jekh** 2016-07-19 15:04 UTC
