### ISSUE TITLE
Pom file question

### ISSUE THREAD

**Issue by gitnava** [lightbody/browsermob-proxy#183] opened 2015-03-05 07:53 UTC
Case 1: Just add the following to pom file
		<dependency>
			<groupId>net.lightbody.bmp</groupId>
			<artifactId>browsermob-proxy</artifactId>
			<version>2.0.0</version>
		</dependency>
Result: SSL test gets a blank page

Case 2: clone master and run mvn command manually to get all the artifacts in place. Add the following to pom file
		<dependency>
			<groupId>net.lightbody.bmp</groupId>
			<artifactId>browsermob-core</artifactId>
			<version>2.1.0-beta-1-SNAPSHOT</version>
		</dependency>
Result: everything works fine! bingo!

Question: How can I set up pom file using 2.0.0 (latest available) and have SSL work fine?? Or when the 2.1.0 beta will be released?

Any help is really appreciated
Thank you!!

**Comment by jekh** [comment] 2015-03-05 20:36
What problems are you having with SSL and 2.0.0? Can you give us more information on the error or issue you're seeing, including how you're invoking using the proxy?

**Comment by gitnava** [comment] 2015-03-05 22:52
Basically the page is not rendering, getting a blank page instead.
Here is the code
    protected void testSetup() throws Exception {    		
    	mobProxyServer = new ProxyServer(MOB_PROXY_PORT);
        Map<String,String> mobProxyServerOptions = new HashMap<String, String>();
        mobProxyServerOptions.put("httpProxy", "<proxyHost>:<proxyPort>");
	mobProxyServer.start();
	mobProxyServer.newHar(test_server);
       mobProxyServer.setCaptureHeaders(true);
       mobProxyServer.setCaptureContent(true);

       Proxy mobProxySeleniumClient = new Proxy();
       String mobProxyString = MOB_PROXY_HOST + ":" + MOB_PROXY_PORT;
		
	mobProxySeleniumClient = mobProxyServer.seleniumProxy();
	mobProxySeleniumClient.setHttpProxy(mobProxyString);
	mobProxySeleniumClient.setSslProxy(mobProxyString); //trustAllSSLCertificates 
	webDriver = createWebDriver(mobProxySeleniumClient);
    }   
    
    private static WebDriver createWebDriver(Proxy proxy){
	DesiredCapabilities capabilities = new DesiredCapabilities();		
	FirefoxProfile profile = new FirefoxProfile();
	
	profile.setAcceptUntrustedCertificates(true);
	profile.setAssumeUntrustedCertificateIssuer(false);
	profile.setPreference("network.proxy.no_proxies_on", "");
	profile.setPreference("network.proxy.type", 1);
	profile.setPreference("security.OCSP.enabled", 0);
	profile.setPreference("network.proxy.http", "localhost");
	profile.setPreference("network.proxy.http_port", 8165);
	proxy.setProxyType(Proxy.ProxyType.MANUAL);		
		
	capabilities.setCapability(FirefoxDriver.PROFILE, profile);
	capabilities.setCapability(CapabilityType.PROXY, proxy);
	capabilities.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
	WebDriver driver = new FirefoxDriver(capabilities);
	return driver;
    }

**Comment by gitnava** [comment] 2015-03-05 22:55
here is the error: basically a webdriver error because element wasnt found, blank page.
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running TestSuite
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/mnava/.m2/repository/org/slf4j/slf4j-simple/1.7.10/slf4j-simple-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/mnava/.m2/repository/org/slf4j/slf4j-nop/1.5.3/slf4j-nop-1.5.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/mnava/.m2/repository/org/slf4j/slf4j-jdk14/1.5.6/slf4j-jdk14-1.5.6.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]
java.lang.NullPointerException
	at net.lightbody.bmp.proxy.ProxyServer.cleanup(ProxyServer.java:127)
	at net.lightbody.bmp.proxy.ProxyServer.stop(ProxyServer.java:131)
	at com.fandango.test.FandangoLightbodyProxy.testSetup(FandangoLightbodyProxy.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:72)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:88)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.booter.ProviderFactory$ClassLoaderProxy.invoke(ProviderFactory.java:103)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:150)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcess(SurefireStarter.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:69)
[main] INFO net.lightbody.bmp.proxy.jetty.http.HttpServer - Version Jetty/5.1.x
[main] INFO net.lightbody.bmp.proxy.jetty.util.Container - Started HttpContext[/,/]
[main] INFO net.lightbody.bmp.proxy.jetty.http.SocketListener - Started SocketListener on 0.0.0.0:8165
[main] INFO net.lightbody.bmp.proxy.jetty.util.Container - Started net.lightbody.bmp.proxy.jetty.jetty.Server@60174a7a
Starting test: verifythreatmetrix
[SocketListener0-1] INFO net.lightbody.bmp.proxy.jetty.util.Credential - Checking Resource aliases
[SocketListener0-1] INFO net.lightbody.bmp.proxy.jetty.http.SocketListener - Started SocketListener on 0.0.0.0:53876
[SocketListener0-0] INFO net.lightbody.bmp.proxy.jetty.http.SocketListener - Started SocketListener on 0.0.0.0:53882
[SeleniumProxyHandler$SslRelay2-1] WARN net.lightbody.bmp.proxy.jetty.http.HttpConnection - GET https://tickets.fandango.com:443/fbs/mobile/partners/FBPartnerEGiftCards.aspx?fbordertype=EGiftPartner&ts=&a=12008 HTTP/1.1
java.lang.NoSuchMethodError: org.eclipse.jetty.util.UrlEncoded.decodeTo(Ljava/lang/String;Lorg/eclipse/jetty/util/MultiMap;Ljava/lang/String;)V
	at net.lightbody.bmp.proxy.http.BrowserMobHttpClient.execute(BrowserMobHttpClient.java:715)
	at net.lightbody.bmp.proxy.http.BrowserMobHttpClient.execute(BrowserMobHttpClient.java:591)
	at net.lightbody.bmp.proxy.http.BrowserMobHttpRequest.execute(BrowserMobHttpRequest.java:149)
	at net.lightbody.bmp.proxy.BrowserMobProxyHandler.proxyPlainTextRequest(BrowserMobProxyHandler.java:269)
	at net.lightbody.bmp.proxy.selenium.SeleniumProxyHandler.handle(SeleniumProxyHandler.java:185)
	at net.lightbody.bmp.proxy.jetty.http.HttpContext.handle(HttpContext.java:1509)
	at net.lightbody.bmp.proxy.jetty.http.HttpContext.handle(HttpContext.java:1461)
	at net.lightbody.bmp.proxy.jetty.http.HttpServer.service(HttpServer.java:892)
	at net.lightbody.bmp.proxy.jetty.http.HttpConnection.service(HttpConnection.java:815)
	at net.lightbody.bmp.proxy.jetty.http.HttpConnection.handleNext(HttpConnection.java:981)
	at net.lightbody.bmp.proxy.jetty.http.HttpConnection.handle(HttpConnection.java:832)
	at net.lightbody.bmp.proxy.jetty.http.SocketListener.handleConnection(SocketListener.java:245)
	at net.lightbody.bmp.proxy.jetty.util.ThreadedServer.handle(ThreadedServer.java:357)
	at net.lightbody.bmp.proxy.jetty.util.ThreadPool$PoolThread.run(ThreadPool.java:534)
Threadmetrix ERROR : org.openqa.selenium.NoSuchElementException: Unable to locate element: {"method":"id","selector":"QuantityDropDown"}
Command duration or timeout: 7 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.44.0', revision: '76d78cf323ce037c5f92db6c1bba601c2ac43ad8', time: '2014-10-23 13:11:40'
System info: host: 'mnava-mac.fandangousa.com', ip: '10.56.81.86', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.5', java.version: '1.7.0_60-ea'
Session ID: 1a603eb0-6d8a-024f-a269-5561950606d9
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=MAC, acceptSslCerts=true, javascriptEnabled=true, cssSelectorsEnabled=true, databaseEnabled=true, browserName=firefox, handlesAlerts=true, nativeEvents=false, webStorageEnabled=true, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=34.0.5}]
[Acceptor [SSL: ServerSocket[addr=0.0.0.0/0.0.0.0,localport=53876]]] INFO net.lightbody.bmp.proxy.jetty.util.ThreadedServer - Stopping Acceptor [SSL: ServerSocket[addr=0.0.0.0/0.0.0.0,localport=53876]]
[SeleniumProxyHandler$SslRelay2-1] WARN net.lightbody.bmp.proxy.BrowserMobProxyHandler - IOException while trying to report an HTTP error
java.io.IOException: closed
	at net.lightbody.bmp.proxy.jetty.http.HttpOutputStream.prepareOutput(HttpOutputStream.java:444)
	at net.lightbody.bmp.proxy.jetty.http.HttpOutputStream.write(HttpOutputStream.java:413)
	at net.lightbody.bmp.proxy.jetty.http.HttpOutputStream.write(HttpOutputStream.java:406)
	at net.lightbody.bmp.proxy.BrowserMobProxyHandler.reportError(BrowserMobProxyHandler.java:312)
	at net.lightbody.bmp.proxy.BrowserMobProxyHandler.access$200(BrowserMobProxyHandler.java:26)
	at net.lightbody.bmp.proxy.BrowserMobProxyHandler$1.reportError(BrowserMobProxyHandler.java:265)
	at net.lightbody.bmp.proxy.http.BrowserMobHttpClient.execute(BrowserMobHttpClient.java:832)
	at net.lightbody.bmp.proxy.http.BrowserMobHttpClient.execute(BrowserMobHttpClient.java:591)
	at net.lightbody.bmp.proxy.http.BrowserMobHttpRequest.execute(BrowserMobHttpRequest.java:149)
	at net.lightbody.bmp.proxy.BrowserMobProxyHandler.proxyPlainTextRequest(BrowserMobProxyHandler.java:269)
	at net.lightbody.bmp.proxy.selenium.SeleniumProxyHandler.handle(SeleniumProxyHandler.java:185)
	at net.lightbody.bmp.proxy.jetty.http.HttpContext.handle(HttpContext.java:1509)
	at net.lightbody.bmp.proxy.jetty.http.HttpContext.handle(HttpContext.java:1461)
	at net.lightbody.bmp.proxy.jetty.http.HttpServer.service(HttpServer.java:892)
	at net.lightbody.bmp.proxy.jetty.http.HttpConnection.service(HttpConnection.java:815)
	at net.lightbody.bmp.proxy.jetty.http.HttpConnection.handleNext(HttpConnection.java:981)
	at net.lightbody.bmp.proxy.jetty.http.HttpConnection.handle(HttpConnection.java:832)
	at net.lightbody.bmp.proxy.jetty.http.SocketListener.handleConnection(SocketListener.java:245)
	at net.lightbody.bmp.proxy.jetty.util.ThreadedServer.handle(ThreadedServer.java:357)
	at net.lightbody.bmp.proxy.jetty.util.ThreadPool$PoolThread.run(ThreadPool.java:534)
[SeleniumProxyHandler$SslRelay2-1] INFO net.lightbody.bmp.proxy.http.BrowserMobHttpClient - EOFException(java.net.SocketException: Broken pipe) when requesting https://tickets.fandango.com/favicon.ico
[SeleniumProxyHandler$SslRelay2-1] WARN net.lightbody.bmp.proxy.jetty.http.HttpConnection - Invalid length: Content-Length=65158 written=7917 for https://tickets.fandango.com/favicon.ico
[main] INFO net.lightbody.bmp.proxy.jetty.http.SocketListener - Stopped SocketListener on 0.0.0.0:53876
[Acceptor [SSL: ServerSocket[addr=0.0.0.0/0.0.0.0,localport=53882]]] INFO net.lightbody.bmp.proxy.jetty.util.ThreadedServer - Stopping Acceptor [SSL: ServerSocket[addr=0.0.0.0/0.0.0.0,localport=53882]]
[main] INFO net.lightbody.bmp.proxy.jetty.http.SocketListener - Stopped SocketListener on 0.0.0.0:53882
[Acceptor ServerSocket[addr=/0.0.0.0,localport=8165]] INFO net.lightbody.bmp.proxy.jetty.util.ThreadedServer - Stopping Acceptor ServerSocket[addr=/0.0.0.0,localport=8165]
[main] INFO net.lightbody.bmp.proxy.jetty.http.SocketListener - Stopped SocketListener on 0.0.0.0:8165
[main] INFO net.lightbody.bmp.proxy.jetty.util.Container - Stopped HttpContext[/,/]
[main] INFO net.lightbody.bmp.proxy.jetty.util.Container - Stopped net.lightbody.bmp.proxy.jetty.jetty.Server@60174a7a
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 13.014 sec <<< FAILURE!

**Comment by jekh** [comment] 2015-03-06 00:46
I see this error in the log:
```
java.lang.NoSuchMethodError: org.eclipse.jetty.util.UrlEncoded.decodeTo(Ljava/lang/String;Lorg/eclipse/jetty/util/MultiMap;Ljava/lang/String;)V
```

Generally that is caused by an incompatibility between the Jetty version that BMP is using and the Jetty version your application uses. It looks like you're running BMP in embedded mode (not using the command-line REST API), so you don't even need to include BMP's Jetty dependency. You can exclude it using the standard Maven dependency exclusion:
```xml
<dependency>
    <groupId>net.lightbody.bmp</groupId>
    <artifactId>browsermob-proxy</artifactId>
    <version>2.0.0</version>
    <scope>test</scope>
    <exclusions>
        <exclusion>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-server</artifactId>
        </exclusion>
        <exclusion>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-servlet</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```
BMP 2.1 separates the REST API from the BMP core (embedded mode) dependency, so that's probably why 2.1 works for you. The beta-1 release is nearing, but it isn't imminent, so if you want to use 2.1, you'll have to use the snapshot version for now.

Hope that helps!

**Comment by gitnava** [comment] 2015-03-06 01:13
Great thank you!!!
I just commented out the following and it works now. Thanks

**Comment by jekh** [comment] 2015-03-16 04:25
Closing because the issue seems to be resolved.

**Closed by jekh** 2015-03-16 04:25 UTC

**Comment by charmsiva** [comment] 2015-11-03 13:31
Still i have faced this issue
java.lang.NoSuchMethodError: org.eclipse.jetty.util.UrlEncoded.decodeTo(Ljava/lang/String;Lorg/eclipse/jetty/util/MultiMap;Ljava/lang/String;)V
this is my pom.xml file
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.sorc.qa.selenium.utils</groupId>
	<artifactId>SeleniumUtils</artifactId>
	<version>1.0-SNAPSHOT</version>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<serenity.version>1.1.3</serenity.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-junit</artifactId>
			<version>${serenity.version}</version>
		
		</dependency>
		<dependency>
			<groupId>net.lightbody.bmp</groupId>
			<artifactId>browsermob-proxy</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.seleniumhq.selenium</groupId>
					<artifactId>selenium-api</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.httpcomponents</groupId>
					<artifactId>httpclient</artifactId>				
				</exclusion>
				<exclusion>
					<groupId>org.slf4j</groupId>
					<artifactId>slf4j-simple</artifactId>
				</exclusion>
				<exclusion>
		            <groupId>org.eclipse.jetty</groupId>
		            <artifactId>jetty-server</artifactId>
		        </exclusion>
		        <exclusion>
		            <groupId>org.eclipse.jetty</groupId>
		            <artifactId>jetty-servlet</artifactId>
		        </exclusion>
			</exclusions>
			<version>2.0-beta-8</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-browsermob-plugin</artifactId>
			<version>1.1.3</version>		
		</dependency>
		<dependency>
			<groupId>log4j</groupId>
			<artifactId>log4j</artifactId>
			<version>1.2.15</version>
			<exclusions>
				<exclusion>
					<groupId>javax.mail</groupId>
					<artifactId>mail</artifactId>
				</exclusion>
				<exclusion>
					<groupId>javax.jms</groupId>
					<artifactId>jms</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.sun.jdmk</groupId>
					<artifactId>jmxtools</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.sun.jmx</groupId>
					<artifactId>jmxri</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpclient</artifactId>
			<version>4.3.3</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-simple</artifactId>
			<version>1.6.1</version>
		</dependency>
		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-entitymanager</artifactId>
			<version>4.2.0.CR2</version>
		</dependency>
		<dependency>
			<groupId>net.sf.opencsv</groupId>
			<artifactId>opencsv</artifactId>
			<version>2.3</version>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.0</version>
				<configuration>
					<source>1.7</source>
					<target>1.7</target>
				</configuration>
			</plugin>
		</plugins>
	</build>
	<distributionManagement>
		<snapshotRepository>
			<id>snapshots</id>
			<name>snapshots</name>
			<url>http://colblapp1d:8081/artifactory/libs-snapshot-local</url>
		</snapshotRepository>
		<repository>
			<id>central</id>
			<name>central</name>
			<url>http://colblapp1d:8081/artifactory/libs-release-local</url>
		</repository>
	</distributionManagement>
</project>

**Comment by charmsiva** [comment] 2015-11-03 13:31
pls give the solution
