### ISSUE TITLE
Connection was aborted by the software in your host machine

### ISSUE THREAD

**Issue by chemicwepn** [lightbody/browsermob-proxy#303] opened 2015-08-20 04:40 UTC
Here is my code:
 proxy = new BrowserMobProxyServer();
      proxy.setConnectTimeout(20, TimeUnit.SECONDS);
      proxy.setIdleConnectionTimeout(20, TimeUnit.SECONDS);
      proxy.setRequestTimeout(20, TimeUnit.SECONDS);
//      proxy.setMitmDisabled(true);
      proxy.start(0);
      Proxy prox = ClientUtil.createSeleniumProxy(proxy);
      capabilities.setCapability(CapabilityType.PROXY, prox);
      driver = new PhantomJSDriver(capabilities);
      
      // time out for script should not be longer than page load timout.
      driver.manage().timeouts().setScriptTimeout(20, TimeUnit.SECONDS);
      driver.manage().timeouts().pageLoadTimeout(60, TimeUnit.SECONDS);
      driver.getErrorHandler().setIncludeServerErrors(true); 

      // create a new HAR
      proxy.newHar(target);

      driver.get(target);

      // get the HAR data
      Har har = proxy.getHar();       
      proxy.endHar();
      proxy.stop();
      driver.quit();
      return har;

I saw some of these exception in the log, are they bad? and what's cause of those exception? I don't think the page was timing out, if it's so, there would be a timeout exception I believe. 

java.io.IOException: An established connection was aborted by the software in your host machine
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_25]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[?:1.8.0_25]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_25]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_25]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379) ~[?:1.8.0_25]
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:447) ~[browsermob-dist-2.1.0-beta-3-SNAPSHOT.jar:?]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:881) ~[browsermob-dist-2.1.0-beta-3-SNAPSHOT.jar:?]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:241) ~[browsermob-dist-2.1.0-beta-3-SNAPSHOT.jar:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119) [browsermob-dist-2.1.0-beta-3-SNAPSHOT.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [browsermob-dist-2.1.0-beta-3-SNAPSHOT.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [browsermob-dist-2.1.0-beta-3-SNAPSHOT.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [browsermob-dist-2.1.0-beta-3-SNAPSHOT.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [browsermob-dist-2.1.0-beta-3-SNAPSHOT.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111) [browsermob-dist-2.1.0-beta-3-SNAPSHOT.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]

**Comment by jekh** [comment] 2015-09-07 00:01
It looks like your connection is being terminated by some external force. What URL are you hitting?

**Comment by jekh** [comment] 2015-12-28 03:30
I'll go ahead and close this, since there's been no update. Please reopen if you're still seeing the issue.

**Closed by jekh** 2015-12-28 03:30 UTC

**Comment by GayathriN** [comment] 2016-02-05 09:56
am seeing this issue. would like to get this reopened if some one can provide a solution

**Comment by vinaybond** [comment] 2016-03-07 06:55
I am getting this error while using browsermob proxy with robotframework:

PUT /proxy/8090/har (my BMP process is running on 8080 on my localost)

error: [Errno 10053] An established connection was aborted by the software in your host machine

Why BMP has terminated the connection? 

Please let me know if you need more details here.

**Comment by jekh** [comment] 2016-03-07 14:51
As the message indicates, something else on your machine (not BMP) is terminating the connection. My first thought would be firewall/antivirus/network configuration. In any case, I could try to reproduce, but definitely need more information in order to reproduce.

**Comment by vinaybond** [comment] 2016-03-07 14:57
I don't have any configuration for firewall or network which may cause this. 
My webapp takes so much time to load the page (sometime even 3 minutes). So I am running the automation framework with 150 seconds timeout. For some case this works fine, for others, I get this error.

Is there a way in which I can ask BMP not to timeout or termite connection no matter how long it take. I tried /proxy/${port}/timeout and /proxy/${port}/wait  after starting the proxy and initializing first page. But they did not work. May be my syntax is wrong. If you can show me if how to use such thing. It will be helpful.



-Vinay

**Comment by jekh** [comment] 2016-03-07 15:18
Which version of BMP are you using? Since you're using the REST API, are you using the littleproxy version or the legacy version? Before you make the request through the browser, try setting the requestTimeout, readTimeout, and connectionTimeout values to something very high.

**Comment by vinaybond** [comment] 2016-03-08 05:41
I am using this version: browsermob-proxy-2.1.0-beta-4
I am using BMP with selenium (using robotframework). Here is I am doing it and getting error for setting timeout. Can you pls tell me how to set timeout correctly.


```
Create http context	localhost:8080	http	
Post	/proxy		
${json}	Get Response Body		
${port}=	Get Json Value	${json}	/port
Set Request Body	requestTimeout=-1&readTimeout=0&dnsCacheTimeout=0&connectionTimeout=0
PUT	/proxy/${port}/timeout
Set Request Body	initialPageRef=LOGIN&captureContent=true&captureHeaders=true
PUT	/proxy/${port}/har
```
Then I am starting the browser using proxy of localhost and ${port}. 

In this case, I am given error that 

`Request should have succeeded, but was "500 Exception [IllegalStateException - "LittleProxy implementation does not allow changes to connect timeout after proxy has been started"] thrown by event method [public com.google.sitebricks.headless.Reply net.lightbody.bmp.proxy.bricks.ProxyResource.timeout(int,com.google.sitebricks.headless.Request)]  at net.lightbody.bmp.BrowserMobProxyServer.setConnectTimeout(BrowserMobProxyServer.java:870) (See below for entire trace.)".`



-Vinay

**Comment by DidacC91** [comment] 2018-06-05 11:03
The problem is caused by CORS. Allow localhost routes like _http://localhost:8080/reactive-commands_ and error was solved

**Comment by gtkpr** [comment] 2018-07-27 04:32
@dcasanovas91 how do i allow that exactly??

**Comment by gtkpr** [comment] 2018-07-27 04:32
out of the blue i'm running into the exact same problem

**Comment by geocode2020** [comment] 2018-11-05 11:20
> 
> 
> The problem is caused by CORS. Allow localhost routes like _http://localhost:8080/reactive-commands_ and error was solved

could you explain to us how did you solve it ?

**Comment by DidacC91** [comment] 2018-11-05 11:31
@mohammed16 download CORS extension in google chrome, enable it and then, in Intercepted URLs copy the route you want.

**Comment by geocode2020** [comment] 2018-11-05 11:42
> 
> 
> @mohammed16 download CORS extension in google chrome, enable it and then, in Intercepted URLs copy the route you want.



I am using Firefox.
