### ISSUE TITLE
Exception on ClientToProxyConnection [/0:0:0:0:0:0:0:1:* => /0:0:0:0:0:0:0:1:*] - java.io.IOException: An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by vkepin** [lightbody/browsermob-proxy#334] opened 2015-11-10 14:48 UTC
Hi,

I use browsermob-core-2.1.0-beta-3 and occasionally I get a such exception:

```
[LittleProxy-0-ClientToProxyWorker-6] ERROR org.littleshoot.proxy.impl.ClientToProxyConnection - (AWAITING_INITIAL) [id: 0x9a08d875, /0:0:0:0:0:0:0:1:65379 => /0:0:0:0:0:0:0:1:65204]: Caught an exception on ClientToProxyConnection
java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_40]
	at sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[?:1.8.0_40]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[?:1.8.0_40]
	at sun.nio.ch.IOUtil.read(Unknown Source) ~[?:1.8.0_40]
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[?:1.8.0_40]
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:447) ~[netty-all-4.0.31.Final.jar:4.0.31.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:881) ~[netty-all-4.0.31.Final.jar:4.0.31.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:242) ~[netty-all-4.0.31.Final.jar:4.0.31.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119) [netty-all-4.0.31.Final.jar:4.0.31.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [netty-all-4.0.31.Final.jar:4.0.31.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [netty-all-4.0.31.Final.jar:4.0.31.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [netty-all-4.0.31.Final.jar:4.0.31.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [netty-all-4.0.31.Final.jar:4.0.31.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [netty-all-4.0.31.Final.jar:4.0.31.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_40]
```

Java-code:
```
BrowserMobProxy proxyServer = new BrowserMobProxyServer();
proxyServer.enableHarCaptureTypes(CaptureType.getHeaderCaptureTypes());
proxyServer.enableHarCaptureTypes(CaptureType.getAllContentCaptureTypes());
proxyServer.start();
```

Could you please take a look? What could be the reason of such exception?
Thanks

**Comment by jekh** [comment] 2015-11-13 23:10
I think the exception message sums it up pretty well: the remove host closed the connection. The logging could be less verbose, but it's pretty common for servers on the internet to close connections prematurely. Are you experiencing any other problems as a result of this?

**Comment by jekh** [comment] 2015-11-13 23:11
By the way, one thing you might try is preferring ipv4 using `-Djava.net.preferIPv4Stack=true`

**Comment by jekh** [comment] 2015-11-30 03:02
@vkepin - any update? Was the work-around I suggested successful?

**Comment by vijaygoturi** [comment] 2015-12-09 06:24
Any workaround for the same issue?

**Comment by jekh** [comment] 2015-12-28 03:22
Since there hasn't been an update from the OP, and a solution was proposed, I'll close this issue.

**Closed by jekh** 2015-12-28 03:22 UTC

**Comment by JuliaSoldatenko** [comment] 2016-01-13 12:48
@jekh , We are still getting the same issue, but with SafariDriver running on SauceLabs. While it doesn't block anything in FF driver, ti's impossible to perform even logIn on Safari,
Is there any other workaround except the one you've suggested?

`-Djava.net.preferIPv4Stack=true` ?

**Comment by jekh** [comment] 2016-01-13 21:27
@JuliaSoldatenko - it sounds like your issue is unrelated to the `An existing connection was forcibly closed by the remote host` error message (which is actually not an error, as explained above). Could you open a new issue with steps to reproduce, along with configuration info?

**Comment by JuliaSoldatenko** [comment] 2016-01-14 16:23
@jekh , thanks for your response! I will double check and open a new one!
