### ISSUE TITLE
Adding a response filter with $' characters duplicates html content

### ISSUE THREAD

**Issue by bmannix** [lightbody/browsermob-proxy#406] opened 2016-03-23 04:35 UTC
Adding a response filter that includes the characters `$'` appears to duplicate some or all of the html content on the page.

The relevant javascript is below:
```javascript
contentType = response.headers().get("content-type");
if (contentType.indexOf("text/html") === 0) {{
og_contents = contents.getTextContents();
h4x0r3d = og_contents.replace("<head>", "<head><script>'^' + '$';###########</script>");
contents.setTextContents(h4x0r3d);
}}
```

A full gist that reproduces the issue using the python bmp bindings is here:
https://gist.github.com/bmannix/f8c5dcddf19489c3f6c4

**Comment by jekh** [comment] 2016-03-24 03:57
This is probably an instance of this: https://bugs.openjdk.java.net/browse/JDK-8076226

Nashorn (the Java 8 javascript engine) is using the javascript String.replace method, rather than java.lang.String. Apparently this is a "feature", not a bug.

The behavior of the special `$'` match in javascript is given here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace
>  	Inserts the portion of the string that follows the matched substring.

If you make the contents of the .replace method conform to the javascript String.replace (e.g. escape the $), it should work for you. Very interesting problem!

**Comment by jekh** [comment] 2016-04-02 22:21
Since the solution has been posted, I'll close this issue.

**Closed by jekh** 2016-04-02 22:21 UTC
