### ISSUE TITLE
Problem of RuntimeException

### ISSUE THREAD

**Issue by digicom1978** [lightbody/browsermob-proxy#338] opened 2015-11-24 16:35 UTC
Hello,

When I launched the protractor, below error message comes out.
The test itself is OK, but I don't know why it happens.

Any comments would be appreciate.

stderr:WARN 11/24 16:08:16 o.e.j.u.log          - /proxy/9000/hosts
com.google.sitebricks.routing.EventDispatchException: Exception [RuntimeException - "Unable to obtain input stream from servlet request (was
 it already used or closed elsewhere?). Error:
No content to map due to end-of-input
 at [Source: org.eclipse.jetty.server.HttpInput@5c082421; line: 1, column: 1]"] thrown by event method [public com.google.sitebricks.headles
s.Reply net.lightbody.bmp.proxy.bricks.ProxyResource.remapHosts(int,com.google.sitebricks.headless.Request)]

at com.google.sitebricks.ServletRequestProvider$1$1.as(ServletRequestProvider.java:67)
(See below for entire trace.)

        at com.google.sitebricks.routing.DefaultPageBook$MethodTuple.call(DefaultPageBook.java:830)
        at com.google.sitebricks.routing.DefaultPageBook$MethodTuple.call(DefaultPageBook.java:805)
        at com.google.sitebricks.routing.DefaultPageBook$PageTuple.callAction(DefaultPageBook.java:624)
        at com.google.sitebricks.routing.DefaultPageBook$PageTuple.doMethod(DefaultPageBook.java:603)
        at com.google.sitebricks.routing.WidgetRoutingDispatcher.fireEvent(WidgetRoutingDispatcher.java:171)
        at com.google.sitebricks.routing.WidgetRoutingDispatcher.bindAndReply(WidgetRoutingDispatcher.java:102)
        at com.google.sitebricks.routing.WidgetRoutingDispatcher.dispatch(WidgetRoutingDispatcher.java:88)
        at com.google.sitebricks.DebugModeRoutingDispatcher.dispatch(DebugModeRoutingDispatcher.java:56)
        at com.google.sitebricks.SitebricksFilter.doFilter(SitebricksFilter.java:62)
        at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
        at com.google.sitebricks.HiddenMethodFilter.doFilter(HiddenMethodFilter.java:70)
        at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1323)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:474)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:935)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:404)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:870)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
        at org.eclipse.jetty.server.Server.handle(Server.java:346)
        at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
        at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:1051)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:592)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:214)
        at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:520)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:528)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.google.sitebricks.routing.DefaultPageBook$MethodTuple.call(DefaultPageBook.java:820)
        ... 34 more
Caused by: java.lang.RuntimeException: Unable to obtain input stream from servlet request (was it already used or closed elsewhere?). Error:

No content to map due to end-of-input
 at [Source: org.eclipse.jetty.server.HttpInput@5c082421; line: 1, column: 1]
        at com.google.sitebricks.ServletRequestProvider$1$1.as(ServletRequestProvider.java:67)
        at net.lightbody.bmp.proxy.bricks.ProxyResource.remapHosts(ProxyResource.java:456)
        ... 39 more
Caused by: com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: org.eclipse.jetty.server.HttpInput@5c082421; line: 1, column: 1]
        at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3110)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3051)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2207)
        at com.google.sitebricks.client.transport.JacksonJsonTransport.in(JacksonJsonTransport.java:31)
        at com.google.sitebricks.ServletRequestProvider$1$1.as(ServletRequestProvider.java:63)
        ... 40 more

stderr:INFO 11/24 16:08:18 n.l.b.p.j.u.Credent~ - Checking Resource aliases

stderr:INFO 11/24 16:08:19 n.l.b.p.j.h.SocketL~ - Started SocketListener on 0.0.0.0:49909

stderr:INFO 11/24 16:08:19 n.l.b.p.j.h.SocketL~ - Started SocketListener on 0.0.0.0:49917

**Comment by jekh** [comment] 2015-11-30 02:57
I've never seen that error before; I'm wondering if it might be caused by a dependency conflict or something else equally obscure. Can you paste the contents of the HTTP request you're making?

**Comment by jekh** [comment] 2015-12-28 03:23
Since there hasn't been an update, I'll close this issue. @digicom1978, please reopen with additional info if you're still experiencing this issue.

**Closed by jekh** 2015-12-28 03:23 UTC
