### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by chemicwepn** [lightbody/browsermob-proxy#292] opened 2015-08-05 21:15 UTC
1970-01-01 08:01:46,916 [LittleProxy-ClientToProxyWorker-7] io.netty.channel.DefaultChannelPipeline WARN An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.lang.NullPointerException
        at org.littleshoot.proxy.impl.ClientToProxyConnection.timedOut(ClientToProxyConnection.java:455)
        at org.littleshoot.proxy.impl.ProxyConnection.userEventTriggered(ProxyConnection.java:657)
        at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:294)
        at io.netty.handler.timeout.IdleStateHandler.channelIdle(IdleStateHandler.java:322)
        at io.netty.handler.timeout.IdleStateHandler$AllIdleTimeoutTask.run(IdleStateHandler.java:435)
        at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:357)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
        at java.lang.Thread.run(Thread.java:745)

I am getting this exception every now and then. Do you guys know the cause of this? Is it because of the timeout settings I have: 
 proxy = new BrowserMobProxyServer();      
 proxy.setConnectTimeout(30, TimeUnit.SECONDS);
proxy.setRequestTimeout(30, TimeUnit.SECONDS);
proxy.start(0);
driver = new PhantomJSDriver(capabilities);
driver.manage().timeouts().setScriptTimeout(30, TimeUnit.SECONDS);
driver.manage().timeouts().pageLoadTimeout(60, TimeUnit.SECONDS);
proxy.newHar(target);
driver.get(target);
Har har = proxy.getHar();
driver.quit();

Note, I don't stop the proxy everytime I quit the driver. So the proxy keeps running...

**Comment by jekh** [comment] 2015-08-06 01:41
It looks like this is caused by a defect in LittleProxy when the client request times out. I'll open a defect in LP. It should be fairly straightforward to fix.

Thanks for noticing this and pasting the info!

**Comment by jekh** [comment] 2015-08-12 02:48
@chemicwepn - this should now be fixed, after an update to LittleProxy. Can you let me know if you still have issues with it?

**Comment by chemicwepn** [comment] 2015-08-15 21:33
how do I update to use the new version? I a using this setting in pom:

<dependency>
        <groupId>net.lightbody.bmp</groupId>
        
        <artifactId>browsermob-core-littleproxy</artifactId>
        <version>2.1.0-beta-2</version>
    </dependency>

**Comment by jekh** [comment] 2015-08-17 14:52
You'll need to build from master, until there's another beta release that includes the fix. There's a section in the [README file](https://github.com/lightbody/browsermob-proxy#building-the-latest-from-source) explaining how to do so.

**Comment by chemicwepn** [comment] 2015-08-20 04:35
Yo, I ran the new build. Looks like Null pointers are gone. Fix looks good. Thanks for the quick fix.

**Comment by jekh** [comment] 2015-08-20 19:20
Great! I'll close this issue, then.

**Closed by jekh** 2015-08-20 19:20 UTC
