### ISSUE TITLE
SSL support on mobile devices

### ISSUE THREAD

**Issue by galvanu** [lightbody/browsermob-proxy#266] opened 2015-06-22 06:31 UTC
I'm trying to use browsermob proxy with appium (selendroid) in order to integrate it in my automation tests for mobile devices (Android and iOS).

So far, everything looks good except one issue: Https requests are not accepted.
I took the 'cybervillainsCA.cer' installed it on my android device and on my desktop but I still can't catch any https requests.

What am I doing wrong? how can I allow https for mobile devices?

**Comment by jatinkapoor** [comment] 2015-07-30 18:38
@galvanu , @jekh 
i am trying to accomplish the same - using appium to drive the native app on the android device and browsermob proxy to capture the network traffic . But so far i haven't had too much success. I tried doing it manually using Charles proxy and it worked but with appium and browsermob proxy I am not able to make a connection between device and proxy server. 
I also made my device point to the proxy server before hand but i dont think it is able to make the connection.
Here's my code -

    BrowserMobProxy server = new BrowserMobProxyServer();
    server.start(5555);
    Proxy proxy = ClientUtil.createSeleniumProxy(server);
    DesiredCapabilities desiredCapabilities = new DesiredCapabilities();
    desiredCapabilities.setCapability("automationName", "Appium");
    desiredCapabilities.setCapability("platformName", "Android");
    desiredCapabilities.setCapability(CapabilityType.PROXY, proxy);
    desiredCapabilities.setCapability("platformVersion", "5.1.1");
    desiredCapabilities.setCapability("deviceName", "JK");      
    desiredCapabilities.setCapability("app", "C:/testapp/com.xxxxx.android.apk");
    desiredCapabilities.setCapability("appPackage", "com.xxxxx.android");
    desiredCapabilities.setCapability("appActivity", "activities.home.HomeActivity");
    desiredCapabilities.setCapability("noReset",false);
    server.newHar("newHar");
    AndroidDriver driver;
    try {
        driver = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"), desiredCapabilities);

        driver.manage().timeouts().implicitlyWait(180, TimeUnit.SECONDS);
        Har har = server.getHar();
        HarLog log = har.getLog();
        List<HarEntry> entries = new CopyOnWriteArrayList<HarEntry>(log.getEntries());
        System.out.println(entries);
        for (HarEntry entry : entries){
            System.out.println(entry.getRequest().getUrl());
        }

    } catch (MalformedURLException e) {
        // TODO Auto-generated catch block
        e.printStackTrace();
    }
    server.stop();
}

Any help would be appreciated.

**Comment by sanjayahuja** [comment] 2015-09-16 18:05
@jatinkapoor, Hey were you able to monitor network traffic for appium? If yes kindly provide details

**Comment by salemrartin** [comment] 2015-11-05 21:23
@galvanu, @jatinkapoor 
Have you been able to solve this issue? I am having the same issue too

Thanks

**Comment by salemrartin** [comment] 2015-11-11 19:07
I am finally able to overcome the issue I am having with proxying HTTPS traffic through Browsermob Proxy!
My setup is:
- Appium Version 1.4.13 (Draco)
- Oracle Java 8
- Browsermob Proxy 2.1.0 -Beta 3
- Using Android *emulator* with API level 21
- Chrome browser com.android.chrome-43.0.2357.92-12357092-minAPI16.apk

My trials concluded that there is an issue with multiple Google Android emulators when I try to run them from command line with -http-proxy http://xxx.xxx.xxx.xxx 
I was able to overcome this by using an alternative Android emulator from Genymotion: www.genymotion.com

What is really interesting is that using the same exact setup listed above with a physical Android device rather than emulator, I can proxy HTTPS traffic through Browsermob proxy with no problem

So something is not quite right with the way google emulators work when they are proxying HTTPS traffic

**Comment by jekh** [comment] 2016-01-03 22:38
@salemrartin - would you mind trying this again with beta-4 (using the browsermob-core-littleproxy implemetnation, or standalone/command line mode)? It contains better MITM support. Make sure to install the `ca-certificate-rsa.cer` certificate file in the android emulator or android device itself to avoid certificate warnings.

**Comment by jekh** [comment] 2016-04-02 22:19
Since there's been no update in a while, I'll close this issue. There's no inherent reason BMP won't work with a native app, as long as the native app is configured correctly to use BMP.

**Closed by jekh** 2016-04-02 22:19 UTC

**Comment by brtu** [comment] 2016-05-05 20:44
I am getting this issue with beta-6.  Genymotion allows SSL to pass through but the default Android Emulator does not.

**Comment by jekh** [comment] 2016-05-06 02:31
@brtu - Do you have a stack trace from the emulator or the machine running BMP?

**Comment by brtu** [comment] 2016-05-06 07:54
@jekh do you have an example on how to get the stack trace?  I don't see a stack trace from my embedded BrowserMobProxy when the SSL request gets blocked on Android.  Maybe I have to adjust my interceptors?  

here's some more details on what I'm doing:

I am setting proxy.setMitmDisabled(true) and https requests are still unable to pass through for Android Emulator 1.x and 2.0.  When I turn on BrowserMobProxy, launch Android Emulator with the flag -http-proxy 127.0.0.1:8888, then navigate using the default Android browser to https://www.google.com, I get a 302 redirect page with ERR_CONNECTION_REFUSED.  An http website such as http://www.urbandictionary.com loads fine.  

When I open my Android app and login to authenticate using an https request, the request times out and nothing happens.  Would the stack trace show up here in Android logcat?

Performing the same actions, it works with Genymotion.  Also, when I use Charles proxy with HTTP proxying enabled and SSL proxying disabled, I am able to navigate to https://www.google.com and login to my app with https.  I also tried using LittleProxy (without mitm module) and https on Android doesn't work.  I tried using the Jetty-based 2.0.0-beta9 BrowserMobProxy as well, and https on Android doesn't work.

**Comment by narulacool** [comment] 2016-05-09 13:02
@jatinkapoor I am trying to use BrowserMob Proxy in the same way as yours. But it's not working. I am  getting a blank .Har file in the end. Any suggestions?

**Comment by jatinkapoor** [comment] 2016-05-09 15:46
@narulacool   - This is how it worked for me . Make sure the proxy port on the device is same as the port you are starting the proxy server (51664) in the example below.

	        Set<CaptureType> captureTypes = new HashSet<CaptureType>();
		captureTypes.add(CaptureType.REQUEST_CONTENT);
		BrowserMobProxy proxy = new BrowserMobProxyServer();
		proxy.enableHarCaptureTypes(captureTypes);
		proxy.start(51664);
		//System.out.println(proxy.getHarCaptureTypes());
		int port = proxy.getPort();
		System.out.println(port);
                //APPIUM STUFFF
		//START RECORDING
                 proxy.newHar("myNewHar");
                //Final Action on the App.
		// get the HAR data
		Har har = proxy.getHar();
		HarLog log = har.getLog();

**Comment by ronnelpinto** [comment] 2016-06-14 07:23
@jatinkapoor, @narulacool,  I am getting empty har file.
I have set the port to 51664 on the device and tried running the above code snippet. 
The http URL is 127.0.0.1/51664.

Can you please elaborate on how to set up the same.

**Comment by ChiWhiteSox56** [comment] 2016-12-04 02:09
I've been trying to capture analytics data from an Android app using BrowserMob for a few weeks now, and I'm not getting very far. I have no problem capturing the data through Charles, so my proxy/port configuration on my phone is correct. When I run my tests the app launches but I get a blank page, aside from a title bar. The app that I'm trying to test uses a web login, so I'm supposed to be seeing username/password fields and a Sign In button. At this point, I'm pretty sure that the web login page is what's causing the issue. I also tried my code against an app with a native login, and I did not encounter this problem.

Has anyone been able to successfully capture network traffic from an app that uses a web login?

**Comment by ChiWhiteSox56** [comment] 2016-12-04 02:19
I've been trying to capture analytics data from an Android app using BrowserMob for a few weeks now, and I'm not getting very far. I have no problem capturing the data through Charles, so my proxy/port configuration on my phone is correct. When I run my tests the app launches but I get a blank page, aside from a title bar. The app that I'm trying to test uses a web login, so I'm supposed to be seeing username/password fields and a Sign In button. At this point, I'm pretty sure that the web login page is what's causing the issue. I also tried my code against an app with a native login, and I did not encounter this problem.

There is no error on the blank page. I only see an error if I haven't set the network ip or port correctly.

Has anyone been able to successfully capture network traffic from an app that uses a web login?

**Comment by brtu** [comment] 2016-12-04 02:43
@ChiWhiteSox56 Did you install the BrowserMobProxy certificate on the device?  You probably installed one for Charles but not  for BrowserMobProxy.  I'm guessing that the login uses a SSL network call that is getting blocked.

**Comment by ChiWhiteSox56** [comment] 2016-12-04 04:13
@brtu - I did install the certificate for Charles on the device, but I did not install a certificate for BrowserMobProxy. I'll look into this and send an update. Thanks so much for your reply!

**Comment by ChiWhiteSox56** [comment] 2016-12-05 21:21
Hi @brtu - I've been trying to figure out how to install a certificate for BrowserWebProxy on the device that I'm using for testing. I'm not finding much information, and I was wondering if you knew of a reference that you could point me to. Based on what I've read so far, I'm assuming that this certificate is to be installed programmatically - is that correct? Any information that you can provide would be greatly appreciated.

**Comment by brtu** [comment] 2016-12-05 21:36
@ChiWhiteSox56 No problem, I actually went through this same problem several months ago.

Take a look at the "SSL Support" section @ https://github.com/lightbody/browsermob-proxy

The ca-certificate-rsa.cer certificate is the one for BrowserMob proxy.  You can use that one if you don't care too much about the security of your device (i.e. it is a device for testing or something).  You can also generate your own certificate for more security. 

Save that file and then you need to push it to your Android device.  You can do that with the command "adb push ca-certificate-rsa.pem /sdcard/Download" where the first param is the local path of the certificate and second param is the path on the Android device.  Then navigate to that folder on your Android device and there should be some prompts to install/trust the certificate.

**Comment by ChiWhiteSox56** [comment] 2016-12-06 19:09
Hey @brtu - The certificate was the problem! I'm able to capture network traffic and analytic data now. Thanks again for your help!

**Comment by brtu** [comment] 2016-12-06 19:11
@ChiWhiteSox56 Glad to hear that!

**Comment by jekh** [comment] 2016-12-07 05:49
@brtu - Thanks for sharing your solution, glad BMP is working with Android clients. FWIW, BMP's .cer files are just regular PEM-encoded files, so the only thing you need to do to convert it to a .pem file is `cp ca-certificate-rsa.cer ca-certificate-rsa.pem` :)

**Comment by RajeshValakonda** [comment] 2017-05-19 10:27
Hello team, 

Do we need to give proxy address in mobile manually???

**Comment by RajeshValakonda** [comment] 2017-05-19 10:27
Hi Team,

Hope everybody is doing good..

I have requirement like , to inspect HTTP communication going out from your phone without setting proxy in mobile device. There should not be manual intervention to setting proxy. Is there any way to do programatically. Could you please give me idea on this ??

Thanks in Advance

**Comment by RajeshValakonda** [comment] 2017-05-19 10:29
@jatinkapoor  -- Are you giving proxy address in mobile device manually??

**Comment by RajeshValakonda** [comment] 2017-05-24 16:54
@jatinkapoor  : Yes

**Comment by brtu** [comment] 2017-05-24 17:10
@RajeshValakonda For real devices, I have the proxy address set manually.  Maybe you can have your test script set the phone's proxy at the start of the test, and then clear the proxy settings at the end of the test.

If you are using an emulator, there is a setting to set the http proxy for Android emulators on startup.

**Comment by RajeshValakonda** [comment] 2017-05-24 17:34
@brtu : Thanks for the reply. but problem here is there is no option to set the proxy through programatically.

**Comment by SagarBShinde** [comment] 2018-09-10 06:21
Hi all,
I have been working on a requirement to monitor and intercept native app traffic on mobile  device with MITM proxy. I have decided to go with BrowserMob Proxy due to it's API support.
Following is my set up

BMP version 2.1.5 https://github.com/lightbody/browsermob-proxy
Mobile device - OnePlus 2 Android v 6.0.1
Proxy set up on Mobile using Drony https://play.google.com/store/apps/details?
id=org.sandroproxy.drony&hl=en_IN

I have installed BMP SSL certificate on Mobile device

Both Mobile and BMP host are on the same WiFi network

I am not able to establish a connection between BMP and Mobile device.

I have been able to monitor traffic via Charles Proxy however encountering issues with the BMP set up

Getting following error in BMP logs

WARNING: An exception was thrown by org.littleshoot.proxy.impl.ConnectionFlow$2.operationComplete()
net.lightbody.bmp.mitm.exception.MitmException: Error creating SSLEngine for connection to client to impersonate upstream host: null
	at net.lightbody.bmp.mitm.manager.ImpersonatingMitmManager.clientSslEngineFor(ImpersonatingMitmManager.java:227)
	at org.littleshoot.proxy.impl.ProxyToServerConnection$3.execute(ProxyToServerConnection.java:724)
	at org.littleshoot.proxy.impl.ConnectionFlow.doProcessCurrentStep(ConnectionFlow.java:140)
	at org.littleshoot.proxy.impl.ConnectionFlow.processCurrentStep(ConnectionFlow.java:128)
	at org.littleshoot.proxy.impl.ConnectionFlow.advance(ConnectionFlow.java:90)
	at org.littleshoot.proxy.impl.ConnectionFlowStep.onSuccess(ConnectionFlowStep.java:83)
	at org.littleshoot.proxy.impl.ConnectionFlow$2.operationComplete(ConnectionFlow.java:149)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:162)
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95)
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30)
	at org.littleshoot.proxy.impl.ConnectionFlow.doProcessCurrentStep(ConnectionFlow.java:140)
	at org.littleshoot.proxy.impl.ConnectionFlow.access$000(ConnectionFlow.java:14)
	at org.littleshoot.proxy.impl.ConnectionFlow$1.run(ConnectionFlow.java:124)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:73)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:446)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:888)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3849)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4712)
	at net.lightbody.bmp.mitm.manager.ImpersonatingMitmManager.getHostnameImpersonatingSslContext(ImpersonatingMitmManager.java:242)
	at net.lightbody.bmp.mitm.manager.ImpersonatingMitmManager.clientSslEngineFor(ImpersonatingMitmManager.java:223)
	... 22 more
Can anybody give pointers on how we can resolve this error?

**Comment by eyal919** [comment] 2018-10-07 07:27
Did someone find a solution? 
I'm getting same (SagarBShinde) error when starting the proxy using avd command line "-http-proxy http://proxy:12345".
when i setup the proxy in the wifi network (manually) everything works as expected.

**Comment by SagarBShinde** [comment] 2018-10-07 07:42
@eyal919 - Try using a legacy implementation of BMP. I did not encounter this error when the BMP legacy implementation
