### ISSUE TITLE
TransferEncoding header is not proxied

### ISSUE THREAD

**Issue by makmi** [lightbody/browsermob-proxy#189] opened 2015-03-27 12:09 UTC
Inside __SeleniumProxyHandler.java__ there is:

protected StringMap _DontProxyHeaders = new StringMap();
{
  Object o = new Object();
...
  _DontProxyHeaders.put(HttpFields.__TransferEncoding, o);
...
}

which results in __TransferEncoding__ headers to be *removed* from the request. Is that *really* intended? 
In our case we had to comment his line out to properly handle Ajax calls to our server.

**Comment by jekh** [comment] 2015-03-27 18:00
What values are you expeccting to see in the Transfer-Encoding header? Typically Transfer-Encoding is used with the value "chunked" to indicate a chunked transfer, and it is rare to find other values in that header. Ideally your application should not be concerned with Transfer-Encoding, because it only deals with how the message is transmitted, and would be processed by whatever underlying HTTP client your application is using (e.g. a Firefox web browser, Apache HttpClient, Netty, etc.).

To answer your question, the proxy needs to be able to set the Transfer-Encoding header itself, since the way it transmits messages (chunked or un-chunked) may be different from the way the server/client transmitted the message to the proxy. So yes, it is intentionally removed.

**Comment by makmi** [comment] 2015-03-30 08:08
Thanks for quick reply. We have developed a mobile application which interacts with http(s) server and is supposed to operate both in online and offline mode. It is working on Android and uses TransferEncoding header with 'chunked' value when it sends 'data synchronization' requests to the server. If this is removed the synchronization logic breaks down. I am not involved in the application design or development so I is hard for me to justify this solution. From perspective of automated test which I represent using browsermob is useful for  recording requests/responses while testing and inspecting 'synchronization data' when needed. Now I understand that browsermob is not intended for such use and that is fine for us as we can still use it after small modification to _DontProxyHeaders list.

**Comment by jekh** [comment] 2015-03-30 17:56
It sounds like an abuse of the Transfer-Encoding header, one that I would urge the developers to avoid at all costs. (If for some reason you do need to add additional information in HTTP headers, you can simply add new, custom headers to the request. BrowserMob Proxy won't touch custom headers, either.)

Unfortunately that's the best advice I can give for now -- I don't think there's a better solution, other than the customization you've already done.

**Comment by makmi** [comment] 2015-04-16 09:40
Hi Jekh,
I looked again at the request sent by our mobile application. It has TransferEncoding set to 'chunked'. 
The browsermob is removing that header which is fine but does not 'compensate' for that. It should calculate ContentLength header and add it to 'proxied' request. As a result the request passed on does  not have any body (I used Fiddler2 and set EXTRA_JVM_ARGUMENTS inside browsermob start script to set http.proxyHost and http.proxyPort)
This behavior I can observe with browsermob-proxy-2.0.0 running on Windows (in the past same issue showed up on browsermob-proxy-2.0-beta-10-SNAPSHOT on Ubuntu).

**Comment by jekh** [comment] 2015-04-17 23:01
I suspect the issue is something specific to your request, because it would cause severe problems if BMP were not sending Content-Length headers with all non-chunked requests.

Since you've captured the request using fiddler, can you paste the contents of both the pre-proxy and post-proxy request headers?

**Comment by makmi** [comment] 2015-04-22 08:15
My browsermob sits on lkmiemw7eu.rpega.com:9099
My Fiddler sits on lkmiemw7eu.rpega.com:8888

The first request goes directly through Fiddler (see end of this message for requests captured by Fiddler). The second request goes through browsermob proxy (i captured it in fiddler too)

Here is how I was able to reproduce behavior I experienced (from another box on ubuntu):

09:56:08 ~
$ curl --proxy  lkmiemw7eu.rpega.com:8888  -X POST -d @payload2.txt -H "Accept-Language: en-US" -H "Accept-Encoding: gzip, deflate" -H   "Transfer-Encoding: chunked" -H "Connection: Keep-Alive" -H "User-Agent: Mozilla/5.0 (Linux; Android 4.4.2; SM-G900F Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36 AmpWebControl/6.5, build 1355"  -H "Cookie: JSESSIONID=7F52404A1C5D02680725AD32A8A73A4A; __utma=1.1391533915.1421933226.1421933226.1421933226.1;  __utmb=1.2.10.1421933226;  __utmt=1;  __utmc=1;  __utmz=1.1421933226.1.1.utmcsr" -H "Authorization: Basic bWZzdXNlckBtZWVwbGVzOnBlZ2E=" -H "Content-Type:" -H "Accept: */*" "http://httpbin.org/post"
{
  "args": {}, 
  "data": "[{ \"yyy\" : \"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxx\"}]", 
  "files": {}, 
  "form": {}, 
  "headers": {
    "Accept": "*/*", 
    "Accept-Encoding": "gzip, deflate", 
    "Accept-Language": "en-US", 
    "Authorization": "Basic bWZzdXNlckBtZWVwbGVzOnBlZ2E=", 
    "Content-Length": "315", 
    "Cookie": "JSESSIONID=7F52404A1C5D02680725AD32A8A73A4A; __utma=1.1391533915.1421933226.1421933226.1421933226.1;  __utmb=1.2.10.1421933226;  __utmt=1;  __utmc=1;  __utmz=1.1421933226.1.1.utmcsr", 
    "Host": "httpbin.org", 
    "User-Agent": "Mozilla/5.0 (Linux; Android 4.4.2; SM-G900F Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36 AmpWebControl/6.5, build 1355"
  }, 
  "json": [
    {
      "yyy": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxx"
    }
  ], 
  "origin": "91.228.237.250", 
  "url": "http://httpbin.org/post"
}
09:56:31 ~
$ curl --proxy  lkmiemw7eu.rpega.com:9099  -X POST -d @payload2.txt -H "Accept-Language: en-US" -H "Accept-Encoding: gzip, deflate" -H   "Transfer-Encoding: chunked" -H "Connection: Keep-Alive" -H "User-Agent: Mozilla/5.0 (Linux; Android 4.4.2; SM-G900F Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36 AmpWebControl/6.5, build 1355"  -H "Cookie: JSESSIONID=7F52404A1C5D02680725AD32A8A73A4A; __utma=1.1391533915.1421933226.1421933226.1421933226.1;  __utmb=1.2.10.1421933226;  __utmt=1;  __utmc=1;  __utmz=1.1421933226.1.1.utmcsr" -H "Authorization: Basic bWZzdXNlckBtZWVwbGVzOnBlZ2E=" -H "Content-Type:" -H "Accept: */*" "http://httpbin.org/post"
{
  "args": {}, 
  "data": "", 
  "files": {}, 
  "form": {}, 
  "headers": {
    "Accept": "*/*", 
    "Accept-Encoding": "gzip, deflate", 
    "Accept-Language": "en-US", 
    "Authorization": "Basic bWZzdXNlckBtZWVwbGVzOnBlZ2E=", 
    "Cookie": "JSESSIONID=7F52404A1C5D02680725AD32A8A73A4A; __utma=1.1391533915.1421933226.1421933226.1421933226.1;  __utmb=1.2.10.1421933226;  __utmt=1;  __utmc=1;  __utmz=1.1421933226.1.1.utmcsr", 
    "Host": "httpbin.org", 
    "User-Agent": "Mozilla/5.0 (Linux; Android 4.4.2; SM-G900F Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36 AmpWebControl/6.5, build 1355"
  }, 
  "json": null, 
  "origin": "91.228.237.250", 
  "url": "http://httpbin.org/post"
}

------------------------------------------------------------------------------------------------------------------------------
payload2.txt file contains just random json:
[{ "yyy" : "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxx"}]

==========================================================================
Request 1 from Fiddler ==========================================================================
POST http://httpbin.org/post HTTP/1.1
Host: httpbin.org
Connection: Keep-Alive
Accept-Language: en-US
Accept-Encoding: gzip, deflate
Transfer-Encoding: chunked
Connection: Keep-Alive
User-Agent: Mozilla/5.0 (Linux; Android 4.4.2; SM-G900F Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36 AmpWebControl/6.5, build 1355
Cookie: JSESSIONID=7F52404A1C5D02680725AD32A8A73A4A; __utma=1.1391533915.1421933226.1421933226.1421933226.1;  __utmb=1.2.10.1421933226;  __utmt=1;  __utmc=1;  __utmz=1.1421933226.1.1.utmcsr
Authorization: Basic bWZzdXNlckBtZWVwbGVzOnBlZ2E=
Accept: */*

13b
[{ "yyy" : "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxx"}]
0

==========================================================================
Request 2 from Fiddler ==========================================================================
POST http://httpbin.org/post HTTP/1.1
Host: httpbin.org
Accept-Language: en-US
Accept-Encoding: gzip, deflate
User-Agent: Mozilla/5.0 (Linux; Android 4.4.2; SM-G900F Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36 AmpWebControl/6.5, build 1355
Cookie: JSESSIONID=7F52404A1C5D02680725AD32A8A73A4A; __utma=1.1391533915.1421933226.1421933226.1421933226.1;  __utmb=1.2.10.1421933226;  __utmt=1;  __utmc=1;  __utmz=1.1421933226.1.1.utmcsr
Authorization: Basic bWZzdXNlckBtZWVwbGVzOnBlZ2E=
Accept: */*

**Comment by jekh** [comment] 2015-05-04 02:33
@makmi - could you test your scenario again using the LittleProxy implementation? This issue may now be fixed.

**Comment by jekh** [comment] 2015-05-17 04:03
I believe this is fixed in the latest code, so I'm going to go ahead and close it. Please reopen if it is still an issue.

**Closed by jekh** 2015-05-17 04:03 UTC

**Comment by makmi** [comment] 2015-05-29 08:15
Hi jekh,

we use browsermob to simulate various network conditions when running our automated tests against Android/iOS device(s). We do it by changing bandwidth limit up (100000 downstream_kbps)  and down (0 downstream_kbps) .
When I tried using Browsermob with 'use-littleproxy=true' I run into limitation that shows up as following exception:

Exception [IllegalStateException - "LittleProxy implementation does not allow changes to write bandwidth limit after proxy has been started"] thrown by event method [public com.google.sitebricks.headless.Reply net.lightbody.bmp.proxy.bricks.ProxyResource.limit(int,com.google.sitebricks.headless.Request)]

I tracked it to file: browsermob-proxy/browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/BrowserMobProxyServer.java

For iOS device we do *not* need to use-littleproxy option as it is not affected by by transfer encoding issue. From the other hand for Android devices the issue with transfer encoding shows up and we can't use LittleProxy because of what I explained above.

Do you plan to support 'dynamic' bandwidth changes with LittleProxy in near future? Maybe you can suggest some other way to simulate network connectivity with LittleProxy mode?

thanks for any feedback.
makmi

**Comment by jekh** [comment] 2015-05-30 03:56
Thanks for the update, @makmi. I just merged a change that should address this!

**Comment by makmi** [comment] 2015-06-02 12:14
Hi, 
I do not get exceptions now but also limits are not enforced- I am able to browse internet although I set:
http --verbose -f   PUT http://localhost:9090/proxy/9092/limit downstreamKbps=0
http --verbose -f   PUT http://localhost:9090/proxy/9092/limit upstreamKbps=0

I started proxy this way:
/browsermob-proxy-2.1.0-beta-2-SNAPSHOT/bin/browsermob-proxy --port 9090 --use-littleproxy=true

Without littleproxy limits are enforced as expected.

**Comment by jekh** [comment] 2015-06-02 20:45
I didn't realize you were using the REST API. I don't think we have a unit test for limiting bandwidth through the REST API, but it _should_ work, even with LittleProxy. Can you open up a separate issue and put your findings in it?

**Comment by jnatalzia** [comment] 2017-07-18 20:56
Running into this same problem where swapping the limit after the proxy has been started doesn't actually throttle the connection. Did this ever get moved to another issue?
