### ISSUE TITLE
Problem with LittleProxy REST API interceptors

### ISSUE THREAD

**Issue by Sergitclone** [lightbody/browsermob-proxy#542] opened 2016-09-11 23:33 UTC
I noticed that if I use the REST API interceptors with LittleProxy
For example:

> curl -i -X POST -H 'Content-Type: text/plain' -d "request.headers().remove('User-Agent');" http://localhost:8080/proxy/8081/filter/request

LP automatically adds this header to all requests:

`"Content-Length: 0"`

All these headers can't be deleted, because in the session can be a real POST requests (via ajax)
It turns out all the requests are sent as POST. How it is possible to fix it?

**Comment by jekh** [comment] 2016-09-12 02:14
What is the problem exactly?

**Comment by Sergitclone** [comment] 2016-09-12 02:32
The problem is that LP adds an extra header("Content-Length: 0") and the server will accept all requests as sent by the POST method

**Comment by jekh** [comment] 2016-09-12 07:13
I still don't understand what the problem is. Are you saying the payload of the POST isn't 0-length? It's not clear what original you're facing here.

**Comment by Sergitclone** [comment] 2016-09-12 12:48
After I set this filter, all subsequent GET requests to be sent through browsermob-proxy will have this header : "content-length: 0"

> curl -i -X POST -H 'Content-Type: text/plain' -d "request.headers().remove('User-Agent');" http://localhost:8080/proxy/8081/filter/request
> 
> curl GET --proxy 127.0.0.1:8081 http://testdomain.com/headers.php

We'll see

```
Host: testdomain.com <br />
Accept: */* <br />
content-length: 0 <br />
Via: 1.1 browsermobproxy <br />
```


headers.php

```
$headers = getallheaders();
foreach ($headers as $header => $value) {
    echo("$header: $value <br />\n");
}
echo("\r\n<br><br>\r\n");

foreach ( $_SERVER as $name => $value ){
	echo("$name => $value<br>\r\n");	
}
echo("\r\n\r\n<br>POST:<br>\r\n");
foreach ( $_POST as $name => $value ){
	echo("$name => $value<br>\r\n");	
}
echo("\r\n\r\n<br>GET:<br>\r\n");
foreach ( $_GET as $name => $value ){
	echo("$name => $value<br>\r\n");	
}
```

**Comment by jekh** [comment] 2016-09-12 19:10
The Content-Length header is added by design. It allows the proxy to keep the connection open after the request is sent. Is this causing some problem for you?

**Comment by jekh** [comment] 2016-12-10 22:48
No updates, so I'll close this.

**Closed by jekh** 2016-12-10 22:48 UTC
