### ISSUE TITLE
HAR file captured from Selenium Webdriver is always corrupt and proxy is enabled automtically in system after test run

### ISSUE THREAD

**Issue by leslyarun** [lightbody/browsermob-proxy#298] opened 2015-08-15 10:14 UTC
I'm using the following codes with Selenium, to capture network traffic in HAR file:

```
public class LoginTest {

	public WebDriver driver;
	BrowserMobProxy server = new BrowserMobProxyServer();
	DesiredCapabilities ieCapabilities  = DesiredCapabilities.internetExplorer();

  @Test
  @Parameters({ "strUserName", "strPasword" })
  public void loginCheck(String strUserName, String strPasword) throws IOException {

	  LoginH objLogin = open("/abs/login",LoginH.class);
	  objLogin.loginTo(strUserName, strPasword);
	  $(byText("Please Login")).should(disappear);
	  Reporter.log("Login Success");
  }

  @BeforeSuite
  public void beforeSuite() throws IOException {

	  File file = new File("C:\\IEDriverServer.exe");
	  System.setProperty("webdriver.ie.driver", file.getAbsolutePath());
	  ieCapabilities .setCapability("ignoreZoomSetting", true);
	  ieCapabilities .setCapability("nativeEvents", false);

      server.enableHarCaptureTypes(CaptureType.getRequestCaptureTypes());
      server.enableHarCaptureTypes(CaptureType.getResponseCaptureTypes());

      // get the selenium proxy object
      Proxy seleniumProxy = ClientUtil.createSeleniumProxy(server);
      ieCapabilities.setCapability(CapabilityType.PROXY, seleniumProxy);
   
      server.newHar("hh");
      driver= new InternetExplorerDriver(ieCapabilities);
      WebDriverRunner.setWebDriver(driver);

	  baseUrl="http://abcd.com";
	  timeout = 40000;
	  startMaximized = true;
  }

  @AfterSuite
  public void afterSuite() throws IOException {

		// get the HAR data
	      Har har = server.getHar();

	   // Write the HAR Data in a File
	   		File harFile = new File("F:\\Traffic"+" 1"+".har");
	   		har.writeTo(harFile);
	  closeWebDriver();
	  server.stop();
  }

}

```

But when I visualize the generated HAR file in www.softwareishard.com/har/viewer/ , it always says,  log.entries[somenumber].response	is missing and it is not optional.

Also after test execution, my proxy address is automatically enabled with the port number used by Browsermob. I dont want my system's proxy settings to be changed after test run 

Please tell me If I'm doing anything wrongly. Above code uses Selenide API for Webdriver

**Comment by jpereira06** [comment] 2015-08-17 07:54
I'm getting the same problem with some pages.. I do not know why but sometimes the response node of some request is null. I'm hacking the error removing the entries with null response... Does anyone have a solution?

**Comment by jekh** [comment] 2015-08-17 15:03
This looks like it might be a duplicate of #285, which was fixed in master a few weeks ago. Can you both try the latest code in master and let me know?

**Comment by jpereira06** [comment] 2015-08-18 14:06
It works for me.

thanks!

**Comment by leslyarun** [comment] 2015-08-24 11:51
@jekh  Can u pls tell me how to use the latest master code?
````
<dependency>
        <groupId>net.lightbody.bmp</groupId>
        <artifactId>browsermob-core-littleproxy</artifactId>
        <version>2.1.0-beta-3-SNAPSHOT</version>
        <scope>test</scope>
    </dependency>
````
Using the above shows me maven error. 
sorry im new to maven, pls help me out

**Comment by jekh** [comment] 2015-08-24 21:33
There are instructions for building from source in the README file/main github page. Or you can wait for the next release to Central.

**Comment by jekh** [comment] 2015-09-01 03:59
Since the original issue is closed, I'm going to go ahead and close this.

**Closed by jekh** 2015-09-01 03:59 UTC

**Comment by leslyarun** [comment] 2015-09-24 08:05
'''' 
<dependency>
	<groupId>net.lightbody.bmp</groupId>
	<artifactId>browsermob-core-littleproxy</artifactId>
	<version>2.1.0-beta-3</version>
</dependency>
''''
After adding this, it is showing :
Missing artifact net.lightbody.bmp:browsermob-core-littleproxy:jar:2.1.0-beta-3

**Comment by jekh** [comment] 2015-09-26 21:11
Seems like a local configuration issue. The artifact is definitely uploaded to maven central. Make sure you don't have any typos, perhaps? Here's the maven reference: http://mvnrepository.com/artifact/net.lightbody.bmp/browsermob-core-littleproxy/2.1.0-beta-3

**Comment by paresh996** [comment] 2017-06-10 14:40
Use PhantomJS with BrowserMobProxy. PhantomJS helps us for JavaScript enables pages. The following code works for HTTPS web addresses, too.

Place **'phantomjs.exe'** in C drive and you get the **'HAR-Information.har'** file in C drive itself.

```
package makemyhar;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import net.lightbody.bmp.BrowserMobProxy;
import net.lightbody.bmp.BrowserMobProxyServer;
import net.lightbody.bmp.core.har.Har;
import net.lightbody.bmp.proxy.CaptureType;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.phantomjs.PhantomJSDriver;
import org.openqa.selenium.phantomjs.PhantomJSDriverService;
import org.openqa.selenium.remote.CapabilityType;
import org.openqa.selenium.remote.DesiredCapabilities;

public class MakeMyHAR {
    public static void main(String[] args) throws IOException, InterruptedException {
        
        //BrowserMobProxy
        BrowserMobProxy server = new BrowserMobProxyServer();
        server.start(0);
        server.setHarCaptureTypes(CaptureType.getAllContentCaptureTypes());
        server.enableHarCaptureTypes(CaptureType.REQUEST_CONTENT, CaptureType.RESPONSE_CONTENT);
        server.newHar("Google");
        
        //PHANTOMJS_CLI_ARGS
        ArrayList<String> cliArgsCap = new ArrayList<>();
        cliArgsCap.add("--proxy=localhost:"+server.getPort());
        cliArgsCap.add("--ignore-ssl-errors=yes");
        
        //DesiredCapabilities
        DesiredCapabilities capabilities = new DesiredCapabilities();
	capabilities.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
        capabilities.setCapability(CapabilityType.SUPPORTS_JAVASCRIPT, true);
        capabilities.setCapability(PhantomJSDriverService.PHANTOMJS_CLI_ARGS, cliArgsCap);
        capabilities.setCapability(PhantomJSDriverService.PHANTOMJS_EXECUTABLE_PATH_PROPERTY,"C:\\phantomjs.exe");
	
        //WebDriver
        WebDriver driver = new PhantomJSDriver(capabilities);
	driver.get("https://www.google.co.in/");
        
        //HAR
        Har har = server.getHar();
        FileOutputStream fos = new FileOutputStream("C:\\HAR-Information.har");
        har.writeTo(fos);
        server.stop();
    }
}

```

**Comment by shahnawazm786** [comment] 2024-05-12 11:02
I am getting empty HAR file, using selenium 4, any solution is much appreciated .
{"log":{"version":"1.2","creator":{"name":"BrowserMob Proxy","version":"2.1.5","comment":""},"pages":[{"id":"Page 0","startedDateTime":"2024-05-12T10:41:08.005Z","title":"Page 0","pageTimings":{"comment":""},"comment":""}],"entries":[],"comment":""}}
