### ISSUE TITLE
Proxy is not working on Mac OSX Yosemite

### ISSUE THREAD

**Issue by sahajamit** [lightbody/browsermob-proxy#193] opened 2015-04-07 09:16 UTC
I am using the BMP 2.0.0 release version and starting the server using the following java code:

server=new ProxyServer();
        server.setPort(8020);
        server.start();

On the console it shows the correct message:

Apr 07, 2015 2:33:19 PM net.lightbody.bmp.proxy.jetty.http.HttpServer doStart
INFO: Version Jetty/5.1.x
Apr 07, 2015 2:33:19 PM net.lightbody.bmp.proxy.jetty.util.Container start
INFO: Started HttpContext[/,/]
Apr 07, 2015 2:33:19 PM net.lightbody.bmp.proxy.jetty.http.SocketListener start
INFO: Started SocketListener on 0.0.0.0:8020
Apr 07, 2015 2:33:19 PM net.lightbody.bmp.proxy.jetty.util.Container start
INFO: Started net.lightbody.bmp.proxy.jetty.jetty.Server@4b6995a2

But when I am trying to use this proxy in the browser, it keeps loading the website. Also I tried to hit the proxy url http://localhost:8020/   but it keeps loading the page.

These same configurations are working on Windows 7. On windows, after staring the server from Java (same as above) code , when I hit this url http://localhost:8020/  it shows this (which I guess is expected)

![screen shot 2015-04-07 at 2 51 31 pm](https://cloud.githubusercontent.com/assets/358319/7020335/cc7678c8-dd35-11e4-8836-9b102b3b4b07.png)

**Comment by jekh** [comment] 2015-04-08 19:37
Can you elaborate on what you mean by "it keeps loading the website"? I'd suggest double-checking the proxy configuration in OS X and in the browser (which browser are you using?). Unfortunately I don't have an OS X machine to repro the issue on.

**Comment by gempesaw** [comment] 2015-04-08 23:48
FWIW, I'm on Yosemite using the exact same version of the proxy (as well as the 2.1.0-next branch) and not having any problems. If it turns out to require a Yosemite box for reproduction, I can pitch in.

**Comment by nthexwn** [comment] 2015-05-01 04:52
I may be experiencing the same issue:  https://groups.google.com/forum/#!topic/browsermob-proxy/1X2OTEuor38

I'm also on Yosemite, and the browser also just "keeps loading" (Chrome times out "waiting on proxy tunnel").  I'd definitely like to compare notes with somebody else and see if we can narrow this down more.

**Comment by romovs** [comment] 2015-05-01 15:38
> I'm also on Yosemite, and the browser also just "keeps loading" (Chrome times out "waiting on proxy tunnel")

Oh I have seen this on rare occasions on Linux and Windows with the old 2.0-beta-9 version (that is pre LittleProxy). Unfortunately I was unable to reliably reproduce it in order do any debugging so we just learned to live with it :cry:

Does it happen for you only with some specific site?

> After the proxy starts and the Selenium WebDriver makes the first navigation request the browser hangs for about 2 minutes before anything shows up. When it does all of the images are stripped from the page and the text is aligned very strangely.

Can you check if Chrome's Developer Tools->Network shows anything unusual? Perhaps browser just blocks HTTPS resources due to self-signed certificate.

**Comment by jekh** [comment] 2015-05-04 02:21
@sahajamit - the error you saw may have been caused by issue #212 that was resolved by an update to LittleProxy. Can you re-pull the latest from master and test your scenario again?

**Comment by jekh** [comment] 2015-05-17 20:34
I'm going to close this issue since it's most likely resolved by the recent Transfer-Encoding fixes to LP. @sahajamit - feel free to reopen if you still see this issue.

**Closed by jekh** 2015-05-17 20:34 UTC

**Comment by Dimmetrious** [comment] 2019-06-26 09:35
BrowserMobProxy proxyBrowser = new BrowserMobProxyServer();
        proxyBrowser.start(0);
        Proxy seleniumProxy = ClientUtil.createSeleniumProxy(proxyBrowser);

        seleniumProxy.setHttpProxy("localhost:"+proxyBrowser.getPort());
        seleniumProxy.setSslProxy("localhost:"+proxyBrowser.getPort());

You need to add setHttpProxy and setSslProxy.

Worked for me
